version: "3.8"
services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "9464:9464"
      - "4321:4321"
  jaeger:
    restart: always
    image: jaegertracing/all-in-one
    ports:
      - "4317:4317"
      - "16686:16686"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
volumes:
  grafana-data:
