receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4321

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
