global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'otel-collector'
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9464']
