@host = https://22db-117-6-133-148.ngrok-free.app
### Get Catalogs

GET {{host}}/catalogservice/api/v1/catalogs/
x-query: {"includes": ["CatalogType", "CatalogBrand"]}

Content-Type: application/json

### Get Catalog detail
@catalogId = 90de2b0d-d9de-4267-9237-062cb61fb166
GET {{host}}/catalogservice/api/v1/catalogs/{{catalogId}}
Content-Type: application/json




### Create catalog
POST {{host}}/catalogservice/api/v1/catalogs
Content-Type: application/json

{
  "name": "Samsung Galaxy M55",
  "availableStock": 10,
  "price": 10190000,
  "imageSrc": "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-samsung-galaxy-m55.png",
  "catalogType": {
    "id": null,
    "name": "Điện thoại, Tablet"
  },
  "catalogBrand": {
    "id": null,
    "name": "Samsung"
  }
}





### Active catalog
@productId = c1f98678-9d05-4c2a-ad1d-0c3756e22307

PUT {{host}}/catalogservice/api/v1/catalogs/{{productId}}/active
Content-Type: application/json


### Inactive catalog

PUT {{host}}/catalogservice/api/v1/catalogs/{{productId}}/inactive
Content-Type: application/json




