###
@host = http://localhost:9999/connector

### 
GET {{host}}/connector-plugins


###
GET {{host}}/connectors HTTP/1.1
content-type: application/json


###
GET {{host}}/connectors/user-outbox-source/config HTTP/1.1
content-type: application/json



### GET request to example server
POST {{host}}/connectors HTTP/1.1
Content-Type: application/json

{
  "name": "catalog-outbox-source",
  "config": {
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "sqlserver",
    "database.port": "1433",
    "database.user": "sa",
    "database.password": "@P@ssw0rd02",
    "database.names": "Db",
    "topic.prefix": "catalog",
    "table.include.list": "dbo.CatalogOutboxes",
    "schema.history.internal.kafka.bootstrap.servers": "broker1:29092,broker2:29093,broker3:29094",
    "schema.history.internal.kafka.topic": "catalog.cdc",
    "database.encrypt": false,
    "include.schema.changes": false,
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.debezium.converters.BinaryDataConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8085",
    "tombstones.on.delete": "false",
    "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,



    "transforms": "outbox",
    "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
    "transforms.outbox.table.field.event.key": "AggregateId",
    "transforms.outbox.table.field.event.id": "Id",
    "transforms.outbox.table.field.event.payload": "Payload",
    "transforms.outbox.table.field.event.payload.id": "AggregateId",
    "transforms.outbox.table.fields.additional.placement": "Type:header:eventType",
    "transforms.outbox.route.by.field": "AggregateType",
    "transforms.outbox.table.field.event.type": "Type",
    "poll.interval.ms": "100",
    "transforms.outbox.route.topic.replacement": "catalog_cdc_events"
  }
}
### Remove connector source
DELETE {{host}}/connectors/catalog-outbox-source HTTP/1.1

### Add OrderOutbox

POST {{host}}/connectors HTTP/1.1
Content-Type: application/json

{
  "name": "order-outbox-source",
  "config": {
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "sqlserver",
    "database.port": "1433",
    "database.user": "sa",
    "database.password": "@P@ssw0rd02",
    "database.names": "Db",
    "topic.prefix": "order",
    "table.include.list": "dbo.OrderOutboxes",
    "schema.history.internal.kafka.bootstrap.servers": "broker1:29092,broker2:29093,broker3:29094",
    "schema.history.internal.kafka.topic": "order.cdc",
    "database.encrypt": false,
    "include.schema.changes": false,
    "value.converter.schemas.enable": false,
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.debezium.converters.BinaryDataConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8085",
    "tombstones.on.delete" : "false",
    "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter",



    "transforms": "outbox",
    "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
    "transforms.outbox.table.field.event.key" : "AggregateId",
    "transforms.outbox.table.field.event.id" : "Id",
    "transforms.outbox.table.field.event.payload" : "Payload",
    "transforms.outbox.table.field.event.payload.id" : "AggregateId",
    "transforms.outbox.table.fields.additional.placement": "Type:header:eventType",
    "transforms.outbox.route.by.field" : "AggregateType",
    "transforms.outbox.table.field.event.type": "Type",

    "poll.interval.ms": "100",

    "transforms.outbox.route.topic.replacement": "order_cdc_events"
  }
}
### Remove connector source
DELETE {{host}}/connectors/order-outbox-source HTTP/1.1



### Add Shipper Outbox

POST {{host}}/connectors HTTP/1.1
Content-Type: application/json

{
  "name": "shipper-outbox-source",
  "config": {
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "sqlserver",
    "database.port": "1433",
    "database.user": "sa",
    "database.password": "@P@ssw0rd02",
    "database.names": "Db",
    "topic.prefix": "shipper",
    "table.include.list": "dbo.ShipperOutboxes",
    "schema.history.internal.kafka.bootstrap.servers": "broker1:29092,broker2:29093,broker3:29094",
    "schema.history.internal.kafka.topic": "user.cdc",
    "database.encrypt": false,
    "include.schema.changes": false,
    "value.converter.schemas.enable": false,
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.debezium.converters.BinaryDataConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8085",
    "tombstones.on.delete" : "false",
    "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter",



    "transforms": "outbox",
    "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
    "transforms.outbox.table.field.event.key" : "AggregateId",
    "transforms.outbox.table.field.event.id" : "Id",
    "transforms.outbox.table.field.event.payload" : "Payload",
    "transforms.outbox.table.field.event.payload.id" : "AggregateId",
    "transforms.outbox.table.fields.additional.placement": "Type:header:eventType",
    "transforms.outbox.route.by.field" : "AggregateType",
    "transforms.outbox.table.field.event.type": "Type",

    "poll.interval.ms": "100",

    "transforms.outbox.route.topic.replacement": "shipper_cdc_events"
  }
}
### Remove connector source
DELETE http://localhost:8083/connectors/shipper-outbox-source HTTP/1.1



### Add Customer Outbox

POST {{host}}/connectors HTTP/1.1
Content-Type: application/json

{
  "name": "customer-outbox-source",
  "config": {
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "sqlserver",
    "database.port": "1433",
    "database.user": "sa",
    "database.password": "@P@ssw0rd02",
    "database.names": "Db",
    "topic.prefix": "customer",
    "table.include.list": "dbo.CustomerOutboxes",
    "schema.history.internal.kafka.bootstrap.servers": "broker1:29092,broker2:29093,broker3:29094",
    "schema.history.internal.kafka.topic": "user.cdc",
    "database.encrypt": false,
    "include.schema.changes": false,
    "value.converter.schemas.enable": false,
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.debezium.converters.BinaryDataConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8085",
    "tombstones.on.delete" : "false",
    "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter",



    "transforms": "outbox",
    "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
    "transforms.outbox.table.field.event.key" : "AggregateId",
    "transforms.outbox.table.field.event.id" : "Id",
    "transforms.outbox.table.field.event.payload" : "Payload",
    "transforms.outbox.table.field.event.payload.id" : "AggregateId",
    "transforms.outbox.table.fields.additional.placement": "Type:header:eventType",
    "transforms.outbox.route.by.field" : "AggregateType",
    "transforms.outbox.table.field.event.type": "Type",

    "poll.interval.ms": "100",

    "transforms.outbox.route.topic.replacement": "customer_cdc_events"
  }
}
### Remove connector source
DELETE {{host}}/connectors/customer-outbox-source HTTP/1.1


