###
@host = http://localhost:9999


### Start order
@userId = 76316400-ab73-4bc7-86d0-efb507e01c57
@orderId = b0bf1f31-41c9-4ada-a31c-ddbffb9b37a6


POST {{host}}/orderservice/api/v1/order HTTP/1.1
Content-Type: application/json

{
  "userId": {{userId}},
  "items": [
    {
      "productId": "5c84fb43-8a88-43ce-9ea3-2b5e009eadf1",
      "quantity": 1
    }
  ],
  "orderDate": "2024-12-05T07:47:14.388Z"
}


###  user payment
POST {{host}}/api/v1/payment/payment
Content-Type: application/json

{
  "userId": "{{userId}}",
  "orderId": "{{orderId}}",
  "transactionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
###


GET https://localhost:9200