###
@host = http://localhost:9999


### Start order
@userId = d2a157f0-8717-4044-bf3a-37d06400f9cc
@orderId = 025c13a0-ff97-469b-be6f-b204f1eefd13


POST {{host}}/orderservice/api/v1/order HTTP/1.1
Content-Type: application/json

{
  "userId": "{{userId}}",
  "items": [
    {
      "productId": "d0532497-58f9-40ed-ba95-951254760e3a",
      "quantity": 1
    }
  ],
  "orderDate": "2024-12-05T07:47:14.388Z"
}


###  user payment
POST {{host}}/orderservice/api/v1/payment/payment
Content-Type: application/json

{
  "userId": "{{userId}}",
  "orderId": "{{orderId}}",
  "transactionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
###


GET https://localhost:9200