// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IntegrationEvents
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class ProductCreatedIntegrationEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProductCreatedIntegrationEvent"",""namespace"":""IntegrationEvents"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""Price"",""type"":""float""},{""name"":""CatalogBrandId"",""type"":""string""},{""name"":""CatalogBrandName"",""type"":""string""},{""name"":""CatalogTypeId"",""type"":""string""},{""name"":""CatalogTypeName"",""type"":""string""},{""name"":""Description"",""type"":""string""},{""name"":""Images"",""type"":""string""}]}");
		private string _Id;
		private string _Name;
		private float _Price;
		private string _CatalogBrandId;
		private string _CatalogBrandName;
		private string _CatalogTypeId;
		private string _CatalogTypeName;
		private string _Description;
		private string _Images;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProductCreatedIntegrationEvent._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public float Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				this._Price = value;
			}
		}
		public string CatalogBrandId
		{
			get
			{
				return this._CatalogBrandId;
			}
			set
			{
				this._CatalogBrandId = value;
			}
		}
		public string CatalogBrandName
		{
			get
			{
				return this._CatalogBrandName;
			}
			set
			{
				this._CatalogBrandName = value;
			}
		}
		public string CatalogTypeId
		{
			get
			{
				return this._CatalogTypeId;
			}
			set
			{
				this._CatalogTypeId = value;
			}
		}
		public string CatalogTypeName
		{
			get
			{
				return this._CatalogTypeName;
			}
			set
			{
				this._CatalogTypeName = value;
			}
		}
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		public string Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				this._Images = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Name;
			case 2: return this.Price;
			case 3: return this.CatalogBrandId;
			case 4: return this.CatalogBrandName;
			case 5: return this.CatalogTypeId;
			case 6: return this.CatalogTypeName;
			case 7: return this.Description;
			case 8: return this.Images;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.Price = (System.Single)fieldValue; break;
			case 3: this.CatalogBrandId = (System.String)fieldValue; break;
			case 4: this.CatalogBrandName = (System.String)fieldValue; break;
			case 5: this.CatalogTypeId = (System.String)fieldValue; break;
			case 6: this.CatalogTypeName = (System.String)fieldValue; break;
			case 7: this.Description = (System.String)fieldValue; break;
			case 8: this.Images = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
