name: 🚀 Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    name: 📦 Build and Push Services
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Context
        uses: actions/checkout@v4

      - name: 🛠️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Build and push Docker image Identity Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/IdentityServer/Identity.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IDENTITY_SERVICE_NAME}}:latest

      - name: 📦 Build and push Docker image Catalog Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Catalog/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_CATALOG_SERVICE_NAME}}:latest

      - name: 🛒 Build and push Docker image Basket Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Basket/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_BASKET_SERVICE_NAME}}:latest

      - name: 🚪 Build and push Docker image Gateway Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Proxy/AppGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_GATEWAY_SERVICE_NAME}}:latest

      - name: 📑 Build and push Docker image Order Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Order/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_ORDER_SERVICE_NAME}}:latest

      - name: 👤 Build and push Docker image User Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/UserManager/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_USER_SERVICE_NAME}}:latest

      - name: 🔔 Build and push Docker image Notification Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Notification/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_NOTIFICATION_SERVICE_NAME}}:latest

      - name: 🚚 Build and push Docker image Shipping Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Shipping/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_SHIPPING_SERVICE_NAME}}:latest

      - name: 💳 Build and push Docker image Payment Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Payment/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_PAYMENT_SERVICE_NAME}}:latest

      - name: 🔍 Build and push Docker image Search Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Search/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_SEARCH_SERVICE_NAME}}:latest

      - name: 💬 Build and push Docker image Comment Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Comment/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_COMMENT_SERVICE_NAME}}:latest

