name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:

jobs:
  main:
    name: Build server for movie

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Context
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image Catalog Service - Command Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Catalog/Command/Application/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_COMMAND_SERVICE_NAME}}:latest
      - name: Build and push Docker image Catalog Service - Query Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Catalog/Query/Application/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_QUERY_SERVICE_NAME}}:latest
      

      
        
        
 